version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: coronawatchdb
      POSTGRES_USER: coronawatchuser
      POSTGRES_PASSWORD: corona1
    ports: 
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgres/sample_data